name: CI/CD Pipeline

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Bump patch version
        run: |
          VERSION_FILE=version.txt
          if [ ! -f "$VERSION_FILE" ]; then echo "1.0.0" > $VERSION_FILE; fi
          OLD_VERSION=$(cat $VERSION_FILE)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo $NEW_VERSION > $VERSION_FILE
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$NEW_VERSION

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=${{ env.VERSION }} -t yourdockerhubusername/simple-java-maven-app:${{ env.VERSION }} .


