name: CI/CD Pipeline

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=${{ env.VERSION }} -t bronyakorolyova/simple-java-maven-app:${{ env.VERSION }} .


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker push bronyakorolyova/simple-java-maven-app:${{ env.VERSION }}

