name: CI/CD Pipeline

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Export JAVA_HOME
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV          
      
      - name: Run Secret Scan
        uses: pre-commit/action@v3.0.0

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

      - name: Set VERSION env 
        run: echo "VERSION=${{ steps.bump.outputs.version }}" >> $GITHUB_ENV 

      - name: Build with Maven
        run: mvn clean package
        
      - name: Install OWASP Dependency-Check CLI
        run: |
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip -o dc.zip
          unzip dc.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh \
            --project 'Simple Java Maven App' \
            --scan simple-java-maven-app \
            --format ALL \
            --out dependency-check-report \
            --failOnCVSS 9.0
